sensors:
  - depth_camera_points

depth_camera_points:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  point_cloud_topic: /depth_camera/points
  max_range: 5.0
  point_subsample: 1
  padding_offset: 0.03
  padding_scale: 1.0
  max_update_rate: 10.0
  filtered_cloud_topic: filtered_cloud
